### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by davidmpaz** [qontu/ngx-inline-editor#102]
Hi,
<br />
<br />thanks for this project. I am using this component in an ionic app. I get this error from:  `InputNumberComponent.InputBase.ngOnDestroy` when entering in a view with `inline-editor`s and then just going back in navigation.
<br />
<br />Any idea on what I am missing ?
<br />
<br />The whole stack trace is here, in case it helps
<br />```
<br />ERROR Error: Uncaught (in promise): TypeError: Object.values is not a function
<br />TypeError: Object.values is not a function
<br />    at InputNumberComponent.InputBase.ngOnDestroy (http://172.17.0.1:8100/build/vendor.js:122328:16)
<br />    at callProviderLifecycles (http://172.17.0.1:8100/build/vendor.js:11527:18)
<br />    at callElementProvidersLifecycles (http://172.17.0.1:8100/build/vendor.js:11496:13)
<br />    at callLifecycleHooksChildrenFirst (http://172.17.0.1:8100/build/vendor.js:11480:17)
<br />    at destroyView (http://172.17.0.1:8100/build/vendor.js:12741:5)
<br />    at callViewAction (http://172.17.0.1:8100/build/vendor.js:12887:13)
<br />    at execEmbeddedViewsAction (http://172.17.0.1:8100/build/vendor.js:12825:17)
<br />    at destroyView (http://172.17.0.1:8100/build/vendor.js:12739:5)
<br />    at callViewAction (http://172.17.0.1:8100/build/vendor.js:12887:13)
<br />    at execComponentViewsAction (http://172.17.0.1:8100/build/vendor.js:12799:13)
<br />```
<br />
<br />thanks in advance,
<br />David

**Comment by davidmpaz** [comment]
Sorry for reporting this here. According to [this docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values) a polyfill is needed for when `Object.values()` is not supported. After including polyfill into my app everything works as expected.

Solution:
* Install shim package:
`npm install object.values`
* In `src/app/app.component.ts` constructor,  Add: 
```
if (!('values' in Object)) {
    values.shim();
}
```

**Comment by davidmpaz** [comment]
Hi @xxxtonixxx,

thanks for correcting me about it. I will read more in the direction you point me out. I don't have such `src/polyfills.ts` file in my ionic app and also I am not using `angular-cli` neither. 

thanks!
