### ISSUE TITLE
Support of FontAwesome 5

### ISSUE THREAD

**Issue by ppattard** [qontu/ngx-inline-editor#122]
Hello,

Version 5 of FontAwesome broke totally the compatibility with previous versions :-(. The class="fa fa-xxx" no longer works and instead they propose several types of icons by using fas, far, etc. Besides, some icons have apparently been renamed (at least in the SVG version) such as for instance the cancel icon that is used in this module (is now called fa-times).

I tried to fork the repo to propose a contribution fixing this. But I did not even manage to make it build locally. Probably because I use Angular 5 and few things are broken. 

So sorry I won't be able to help further. But if anyone is willing to port to the new FA version, I would appreciate!

Cheers

**Comment by xxxtonixxx** [comment]
Thanks four your help! what problem do you have to build it? :+1:

**Comment by 360disrupt** [comment]
I also had a problem building it:

```
/node_modules/@qontu/ngx-inline-editor/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import { task, src, dest, watch } from "gulp";
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/user/Projekte/1-NODEJS/git-start-project/frontend/node_modules/@qontu/ngx-inline-editor/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @qontu/ngx-inline-editor@0.2.0-alpha.11 build: `gulp build && echo 'To publish a new version of library, please use npm run publish'`
npm ERR! Exit status 1
```
I forked the package and tried to integrate fa5 in an angular way but I couldn't test it because I wasn't able to build it. 

I made a pull request without building it:
https://github.com/qontu/ngx-inline-editor/pull/149
